version: "3.9"
services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - frontend
      
  frontend:
    build:
      context: ./frontend 
    container_name: frontend  
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/home/app/certs
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
