# version: "3.9"
# services:
#   backend:
#     build: .
#     container_name: backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./core:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - SECRET_KEY=test
#       - DEBUG=True
#       - ALLOWED_HOSTS=*
#     depends_on:
#       - frontend

#   frontend:
#     build:
#       context: ./frontend
#     container_name: frontend
#     command: npm start
#     ports:
#       - "3000:3000"
#     stdin_open: true
#     tty: true

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - backend
#       - frontend


version: "3.9"
services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=*
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
