# Generated by Django 5.1.2 on 2024-10-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
