# Generated by Django 5.1.2 on 2024-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
